### ISSUE TITLE
Meta Cluster

### ISSUE THREAD

**Issue by gurrie** [yammer/breakerbox#10]
Hi

Could you please explain the concept of meta clusters? I am interested in the reason why these aren't configurable? Is this to prevent changes in prod?

Kind Regards
Brian

**Comment by chrisgray** [comment]
Are you referring to this block of code? https://github.com/yammer/breakerbox/blob/master/breakerbox-service/src/main/java/com/yammer/breakerbox/service/core/Instances.java#L33-L50

If so, the idea of MetaClusters was something that actually didn't have specific instances but was made up of multiple difference clusters. Here we often create dashboards that are made up of multiple clusters of instances that represent our deployment environments. You can also imagine dashboards that are feature-focused that are representative of the backing instances.

You raise a good point in that they should be configurable. They absolutely should be configurable. I'll make a point to get that in.

**Comment by chrisgray** [comment]
This is fixed by PR https://github.com/yammer/breakerbox/pull/14 which will be available in the next release

**Comment by gurrie** [comment]
Many thanks for the fix. Apologies for not responding earlier.
