### ISSUE TITLE
Cluster configuration

### ISSUE THREAD

**Issue by gurrie** [yammer/breakerbox#18]
Hi,

With the changes that were introduced as part of 0.4.3, can you please explain what the correct method is to configure breakerbox? Is the config.properties file still valid? It appears that the cluster configuration is now done in the breakerbox.yml file, however how does this work if I need to update the cluster configuration at runtime, i.e. to accomodate new nodes being added to the cluster etc?

Many thanks in advance.

Regards
Brian

**Comment by chrisgray** [comment]
The config.properties style/formatting is no longer valid. I was trying to move towards yaml format to reduce editing and formatting errors that was a lot of people ran into with the system properties format.

However, when moving to the yaml file format for instance discovery I did break ability to edit the file at runtime and those values to be picked up. Sorry for this! I'll fix this very quickly!

**Comment by nimble-software** [comment]
Hi, ok great. Many thanks for the update. For the moment we will stick with an older version.

Thanks for all the great work

**Comment by chrisgray** [comment]
I just released 0.4.3 which has this fix as part of it. I moved the yaml configuration (turbine) to a separate one from the service yaml so those editable instances are isolated in it's own file altogether. Now the behavior should be similar to before where it will constantly refresh instances from the yaml file.

**Comment by gurrie** [comment]
Awesome! You rock, thank you!
