### ISSUE TITLE
KubernetesInstanceDiscovery not removing the pod-template-hash correctly

### ISSUE THREAD

**Issue by nimble-software** [yammer/breakerbox#49]
Hi

I have deployed a breakerbox instance using the KubernetesInstanceDiscovery instanceDiscoveryClass. I am able to see the pods in the dashboard, however there is a dashboard for each pod i.e. 

qa-product-service-67c5b74ddf
qa-product-service-57c5b74dag

rather than a dashboard for qa-product-service etc. This seems to be due to the fact that the pod-template-hash is not being removed, as it is not present in the generated name. Am I doing something wrong?

Regards
Brian

**Comment by nimble-software** [comment]
Hi all, 

Just wanted to check, is this repo still maintained? Appears not from the lack of response, if so what is everyone using now days?

Regards
Brian

**Comment by maksymgendin** [comment]
We are using it.  I have also a pending pull request for Oracle DB which is already open for months 😞

**Comment by nimble-software** [comment]
Ok, time to explore other options I think!

**Comment by maksymgendin** [comment]
@nimble-software Ping me when you've found good alternatives 😄
