### ISSUE TITLE
Getting exception when starting breakerbox with in memory storage

### ISSUE THREAD

**Issue by bansalmudit** [yammer/breakerbox#5]
Exception : 
org.h2.jdbc.JdbcSQLException: Table "SERVICE" not found; SQL statement

Config (breakerbox.yml): 
breakerbox:
  urls: file:config.properties,http://localhost:8080/archaius/breakerbox
  initialDelay: 0s
  delay: 60s

breakerboxHostAndPort: localhost:8080 #default

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:inMemory
  user: breakerbox
  password: breakerboxpass
  maxSize: 10
  minSize: 2
  checkConnectionWhileIdle: true
  checkConnectionHealthWhenIdleFor: 1s

tenacityClient:
  connectionTimeout: 500ms
  timeout: 1000ms

defaultDashboard: production

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  gzip:
    enabled: false

logging:
  level: INFO
  appenders:
    - type: console

config.properties :
turbine.aggregator.clusterConfig=production,breakerbox
turbine.instanceUrlSuffix=/tenacity/metrics.stream
turbine.ConfigPropertyBasedDiscovery.production.instances=localhost:8080,anotherservice.company.com:8080
turbine.ConfigPropertyBasedDiscovery.breakerbox.instances=localhost:8080

**Comment by chrisgray** [comment]
Try adding a DB_CLOSE_DELAY=-1to the URL for h2.

You can see an example here: https://github.com/yammer/breakerbox/blob/master/breakerbox-service/breakerbox.yml#L8
