### ISSUE TITLE
Unable to configure cluster instances with additional URI path

### ISSUE THREAD

**Issue by rlewan** [yammer/breakerbox#6]
We have a service which utilizes Tenacity which we would like to connect to a Breakerbox instance. The problem is that the service exposes its Tenacity resources under an additional context, so they are not where Breakerbox expects them to be by default:

  some-service-inst1:1234**/resilience**/tenacity/propertykeys
  some-service-inst1:1234**/resilience**/tenacity/configuration/{key}
  some-service-inst1:1234**/resilience**/tenacity/circuitbreakers
  ...
  
We thought that in such scenario it would be enough to configure the cluster instances appropriately:
```
  turbine.ConfigPropertyBasedDiscovery.some-service.instances=\
    some-service-inst1:1234/resilience
```    
However, Breakerbox will strip the path part from provided entries and thus attempt to connect to a resource which does not exist. My questions now are:
  - is there a way to configure Breakerbox to support our scenario?
  - was there a particular reason for disallowing additional path on configured cluster instances?

Any info will be appreciated.

Thanks,
Rafal

**Comment by rlewan** [comment]
PS.
I've cloned the project and adjusted code to use configured path (Instances#toPropertyKeyUri). Two Instances class unit tests broke, but after I've force built and launched the Breakerbox it appeared to be functional (this is the reason for my second question).

**Comment by chrisgray** [comment]
Hello!

The configuration for these instances is very fragile so I apologize for the headaches they are causing you. I'll look into changing the Instances#toPropertyKeyUri call so that others can utilize this as well. There is no particular reason why we would not want you to be able to put these resources wherever you'd like.

**Comment by rlewan** [comment]
Thanks for a quick update! Hopefully the fix will make this already awesome application even better :)

Cheers,
Rafal

**Comment by chrisgray** [comment]
You want to get credit for the change? Send me your forked PR :-)

**Comment by chrisgray** [comment]
Just committed a fix for this which will come out in the next release! Thanks for the heads up

**Comment by rlewan** [comment]
Haven't noticed the previous comment, doh ;) 

Thanks for the fix!
